<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.7.1.2',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
    1 => 'CORP',
    2 => 'ENT',
    3 => 'ULT',
  ),
  'readme' => '',
  'key' => 'ums',
  'author' => 'khubaib',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'UMS',
  'published_date' => '2017-07-20 12:10:19',
  'type' => 'module',
  'version' => 1500552619,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'UMS',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'ums_student',
      'class' => 'ums_student',
      'path' => 'modules/ums_student/ums_student.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'ums_course',
      'class' => 'ums_course',
      'path' => 'modules/ums_course/ums_course.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'ums_teacher',
      'class' => 'ums_teacher',
      'path' => 'modules/ums_teacher/ums_teacher.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'ums_class',
      'class' => 'ums_class',
      'path' => 'modules/ums_class/ums_class.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ums_student',
      'to' => 'modules/ums_student',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ums_course',
      'to' => 'modules/ums_course',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ums_teacher',
      'to' => 'modules/ums_teacher',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/ums_class',
      'to' => 'modules/ums_class',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);